-- Seed Data Migration for ZST - All Products and Services
-- This migrates all existing static data to Supabase

-- =====================================================
-- WOMEN'S PERFUMES
-- =====================================================

INSERT INTO public.products (slug, name, brand, price, original_price, category, product_type, product_category, need, in_stock, is_promo, is_new, rating, viewers_count, description, benefits, ingredients, usage_instructions, delivery_estimate, shipping_info, returns_info, payment_info, exclusive_offers) VALUES
('parfum-femme-68000', 'Parfum Femme Prestige', 'ZST', 68000, 68000, 'Santé & Beauté', 'Parfum Femme', 'perfume', 'Soirée', true, false, false, 4.9, 32, 'Un parfum de luxe exceptionnel pour la femme moderne. Une fragrance sophistiquée et mémorable.', ARRAY['Fragrance de luxe', 'Tenue exceptionnelle', 'Bouteille de 10ml', 'Notes orientales envoûtantes'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-femme-11500', 'Parfum Femme Délicat', 'ZST', 11500, 11500, 'Santé & Beauté', 'Parfum Femme', 'perfume', 'Quotidien', true, false, false, 4.6, 28, 'Une fragrance douce et délicate, idéale pour un usage quotidien. Parfait pour la femme active.', ARRAY['Fragrance légère et fraîche', 'Parfait pour tous les jours', 'Bouteille de 10ml', 'Notes florales subtiles'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-femme-11800da', 'Parfum Femme Classique', 'ZST', 11800, 11800, 'Santé & Beauté', 'Parfum Femme', 'perfume', 'Journée', true, false, false, 4.7, 35, 'Un classique intemporel qui ne se démode jamais. Une fragrance élégante pour la femme moderne.', ARRAY['Fragrance classique', 'Tenue longue durée', 'Bouteille de 10ml', 'Notes sophistiquées'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-femme-8000da', 'Parfum Femme Fraîcheur', 'ZST', 8000, 8000, 'Santé & Beauté', 'Parfum Femme', 'perfume', 'Quotidien', true, true, false, 4.5, 42, 'Une fragrance fraîche et énergisante, parfaite pour commencer la journée avec entrain.', ARRAY['Fragrance fraîche', 'Idéal pour le quotidien', 'Bouteille de 10ml', 'Notes agrumes et florales'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-femme-7800da', 'Parfum Femme Sensuel', 'ZST', 7800, 7800, 'Santé & Beauté', 'Parfum Femme', 'perfume', 'Soirée', true, false, false, 4.6, 38, 'Une fragrance sensuelle et envoûtante, parfaite pour les soirées romantiques.', ARRAY['Fragrance sensuelle', 'Parfait pour les soirées', 'Bouteille de 10ml', 'Notes orientales chaudes'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-femme-7500', 'Parfum Femme Élégance', 'ZST', 7500, 7500, 'Santé & Beauté', 'Parfum Femme', 'perfume', 'Journée', true, false, false, 4.7, 29, 'Une fragrance élégante et raffinée qui met en valeur votre féminité.', ARRAY['Fragrance élégante', 'Tenue moyenne', 'Bouteille de 10ml', 'Notes florales raffinées'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-femme-6800', 'Parfum Femme Douceur', 'ZST', 6800, 6800, 'Santé & Beauté', 'Parfum Femme', 'perfume', 'Quotidien', true, false, false, 4.5, 33, 'Une fragrance douce et apaisante, idéale pour un usage quotidien.', ARRAY['Fragrance douce', 'Parfait pour tous les jours', 'Bouteille de 10ml', 'Notes vanillées subtiles'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-femme-6800da', 'Parfum Femme Charme', 'ZST', 6800, 6800, 'Santé & Beauté', 'Parfum Femme', 'perfume', 'Journée', true, false, false, 4.6, 27, 'Un parfum charmeur qui révèle votre personnalité unique et séduisante.', ARRAY['Fragrance charmeuse', 'Tenue moyenne', 'Bouteille de 10ml', 'Notes fruitées et florales'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL);

-- Insert images for women's perfumes
INSERT INTO public.product_images (product_id, image_url, is_primary, display_order)
SELECT id, '/perfums/68000.jpg', true, 0 FROM products WHERE slug = 'parfum-femme-68000' UNION ALL
SELECT id, '/perfums/11500.jpg', true, 0 FROM products WHERE slug = 'parfum-femme-11500' UNION ALL
SELECT id, '/perfums/11800da 10ml.jpg', true, 0 FROM products WHERE slug = 'parfum-femme-11800da' UNION ALL
SELECT id, '/perfums/8000da 10ml.jpg', true, 0 FROM products WHERE slug = 'parfum-femme-8000da' UNION ALL
SELECT id, '/perfums/7800da 10ml.jpg', true, 0 FROM products WHERE slug = 'parfum-femme-7800da' UNION ALL
SELECT id, '/perfums/7500.jpg', true, 0 FROM products WHERE slug = 'parfum-femme-7500' UNION ALL
SELECT id, '/perfums/6800.jpg', true, 0 FROM products WHERE slug = 'parfum-femme-6800' UNION ALL
SELECT id, '/perfums/6800da 10ml.jpg', true, 0 FROM products WHERE slug = 'parfum-femme-6800da';

-- =====================================================
-- MEN'S PERFUMES
-- =====================================================

INSERT INTO public.products (slug, name, brand, price, original_price, category, product_type, product_category, need, in_stock, is_promo, is_new, rating, viewers_count, description, benefits, ingredients, usage_instructions, delivery_estimate, shipping_info, returns_info, payment_info, exclusive_offers) VALUES
('parfum-homme-7500louis', 'Parfum Homme Prestige', 'ZST', 7500, 7500, 'Santé & Beauté', 'Parfum Homme', 'perfume', 'Soirée', true, false, true, 4.8, 52, 'Un parfum masculin prestigieux et sophistiqué, parfait pour l''homme moderne et élégant.', ARRAY['Fragrance masculine puissante', 'Tenue exceptionnelle', 'Bouteille élégante de 10ml', 'Parfait pour les occasions spéciales'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', 'Code promo WELCOME10 pour 10% de réduction sur votre première commande.'),
('parfum-homme-6800da', 'Parfum Homme Fraîcheur', 'ZST', 6800, 6800, 'Santé & Beauté', 'Parfum Homme', 'perfume', 'Quotidien', true, false, false, 4.6, 41, 'Une fragrance fraîche et énergisante, idéale pour l''homme actif au quotidien.', ARRAY['Fragrance fraîche', 'Parfait pour tous les jours', 'Bouteille de 10ml', 'Notes agrumes et boisées'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-homme-6800-10ml', 'Parfum Homme Intense', 'ZST', 6800, 6800, 'Santé & Beauté', 'Parfum Homme', 'perfume', 'Soirée', true, false, false, 4.7, 36, 'Un parfum intense et charismatique qui révèle votre personnalité forte.', ARRAY['Fragrance intense', 'Tenue longue durée', 'Bouteille de 10ml', 'Notes boisées et épicées'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-homme-6200', 'Parfum Homme Élégance', 'ZST', 6200, 6200, 'Santé & Beauté', 'Parfum Homme', 'perfume', 'Journée', true, false, false, 4.5, 31, 'Une fragrance élégante et raffinée pour l''homme distingué.', ARRAY['Fragrance élégante', 'Tenue moyenne', 'Bouteille de 10ml', 'Notes classiques masculines'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-homme-5800', 'Parfum Homme Sport', 'ZST', 5800, 5800, 'Santé & Beauté', 'Parfum Homme', 'perfume', 'Quotidien', true, true, false, 4.4, 44, 'Une fragrance dynamique et sportive, parfaite pour l''homme actif.', ARRAY['Fragrance dynamique', 'Idéal pour le sport', 'Bouteille de 10ml', 'Notes fraîches et énergisantes'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-homme-5500', 'Parfum Homme Classic', 'ZST', 5500, 5500, 'Santé & Beauté', 'Parfum Homme', 'perfume', 'Journée', true, false, false, 4.5, 28, 'Un classique intemporel qui ne se démode jamais. Une fragrance masculine authentique.', ARRAY['Fragrance classique', 'Tenue moyenne', 'Bouteille de 10ml', 'Notes boisées traditionnelles'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-homme-4900', 'Parfum Homme Essence', 'ZST', 4900, 4900, 'Santé & Beauté', 'Parfum Homme', 'perfume', 'Quotidien', true, false, false, 4.3, 25, 'Une essence masculine pure et authentique, parfaite pour un usage quotidien.', ARRAY['Fragrance authentique', 'Parfait pour tous les jours', 'Bouteille de 10ml', 'Notes épicées subtiles'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-homme-580', 'Parfum Homme Fresh', 'ZST', 580, 580, 'Santé & Beauté', 'Parfum Homme', 'perfume', 'Quotidien', true, true, false, 4.2, 48, 'Une fragrance fraîche et légère, idéale pour un usage quotidien à petit prix.', ARRAY['Fragrance fraîche', 'Excellent rapport qualité-prix', 'Bouteille de 10ml', 'Notes agrumes légères'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL),
('parfum-homme-490', 'Parfum Homme Essential', 'ZST', 490, 490, 'Santé & Beauté', 'Parfum Homme', 'perfume', 'Quotidien', true, true, false, 4.1, 39, 'Un parfum essentiel et abordable, parfait pour découvrir notre collection.', ARRAY['Fragrance essentielle', 'Prix abordable', 'Bouteille de 10ml', 'Notes légères et agréables'], 'Eau de Parfum, Alcools, Fragrance', 'Vaporiser sur les zones de pulsation : poignets, cou, derrière les oreilles. 10ml - Parfait pour tester ou voyager.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.', NULL);

-- Insert images for men's perfumes
INSERT INTO public.product_images (product_id, image_url, is_primary, display_order)
SELECT id, '/perfums/7500louis.jpg', true, 0 FROM products WHERE slug = 'parfum-homme-7500louis' UNION ALL
SELECT id, '/perfums/6800da 10.jpg', true, 0 FROM products WHERE slug = 'parfum-homme-6800da' UNION ALL
SELECT id, '/perfums/6800 10ml.jpg', true, 0 FROM products WHERE slug = 'parfum-homme-6800-10ml' UNION ALL
SELECT id, '/perfums/6200.jpg', true, 0 FROM products WHERE slug = 'parfum-homme-6200' UNION ALL
SELECT id, '/perfums/5800.jpg', true, 0 FROM products WHERE slug = 'parfum-homme-5800' UNION ALL
SELECT id, '/perfums/5500.jpg', true, 0 FROM products WHERE slug = 'parfum-homme-5500' UNION ALL
SELECT id, '/perfums/4900.jpg', true, 0 FROM products WHERE slug = 'parfum-homme-4900' UNION ALL
SELECT id, '/perfums/580.jpg', true, 0 FROM products WHERE slug = 'parfum-homme-580' UNION ALL
SELECT id, '/perfums/490.jpg', true, 0 FROM products WHERE slug = 'parfum-homme-490';

-- =====================================================
-- WINTER CLOTHES
-- =====================================================

INSERT INTO public.products (slug, name, brand, price, original_price, category, product_type, product_category, need, in_stock, is_promo, rating, viewers_count, description, benefits, ingredients, usage_instructions, delivery_estimate, shipping_info, returns_info, payment_info) VALUES
('adidas-white-winter', 'Adidas White Winter Jacket', 'Adidas', 8500, 8500, 'Vêtements', 'Parfum Homme', 'clothing', 'Quotidien', true, false, 4.5, 0, 'Veste d''hiver Adidas blanche, élégante et confortable. Parfaite pour affronter les températures froides avec style.', ARRAY['Matériau de haute qualité', 'Confortable et chaud', 'Design moderne', 'Parfait pour l''hiver'], 'Polyester, Coton', 'Porter comme veste d''extérieur pendant les saisons froides.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.'),
('north-face-black', 'North Face Black Jacket', 'North Face', 8500, 8500, 'Vêtements', 'Parfum Homme', 'clothing', 'Quotidien', true, false, 4.7, 0, 'Veste North Face noire, robuste et résistante aux intempéries. Idéale pour les activités de plein air.', ARRAY['Résistant à l''eau', 'Très chaud', 'Durable', 'Style sportif'], 'Nylon, Polyester', 'Porter comme veste d''extérieur pour les activités hivernales.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.'),
('north-face-blue', 'North Face Blue Jacket', 'North Face', 8500, 8500, 'Vêtements', 'Parfum Homme', 'clothing', 'Quotidien', true, false, 4.6, 0, 'Veste North Face bleue, élégante et fonctionnelle. Parfaite pour un look moderne et confortable.', ARRAY['Design élégant', 'Protection contre le vent', 'Confortable', 'Couleur tendance'], 'Nylon, Polyester', 'Porter comme veste d''extérieur pendant les saisons froides.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.'),
('north-face-white', 'North Face White Jacket', 'North Face', 8500, 8500, 'Vêtements', 'Parfum Homme', 'clothing', 'Quotidien', true, false, 4.5, 0, 'Veste North Face blanche, fraîche et moderne. Idéale pour un style décontracté et élégant.', ARRAY['Couleur classique', 'Facile à assortir', 'Confortable', 'Design épuré'], 'Nylon, Polyester', 'Porter comme veste d''extérieur pendant les saisons froides.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.'),
('brown-winter-jacket', 'Brown Winter Jacket', 'ZST', 8500, 8500, 'Vêtements', 'Parfum Homme', 'clothing', 'Quotidien', true, false, 4.4, 0, 'Veste d''hiver marron, chaleureuse et polyvalente. Parfaite pour toutes les occasions.', ARRAY['Couleur intemporelle', 'Très chaud', 'Polyvalente', 'Style classique'], 'Polyester, Coton', 'Porter comme veste d''extérieur pendant les saisons froides.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.'),
('grey-winter-jacket', 'Grey Winter Jacket', 'ZST', 8500, 8500, 'Vêtements', 'Parfum Homme', 'clothing', 'Quotidien', true, false, 4.5, 0, 'Veste d''hiver grise, élégante et moderne. Un essentiel pour votre garde-robe hivernale.', ARRAY['Couleur neutre', 'Facile à assortir', 'Confortable', 'Design moderne'], 'Polyester, Coton', 'Porter comme veste d''extérieur pendant les saisons froides.', 'Livraison estimée sous 2-3 jours', 'Livraison gratuite à partir de 20000 DA. Expédition sous 24-48h.', 'Retours acceptés sous 7 jours.', 'Paiement sécurisé par carte bancaire ou espèces à la livraison.');

-- Insert images for winter clothes
INSERT INTO public.product_images (product_id, image_url, is_primary, display_order)
SELECT id, '/winter/addidaswhite.png', true, 0 FROM products WHERE slug = 'adidas-white-winter' UNION ALL
SELECT id, '/winter/black north face.png', true, 0 FROM products WHERE slug = 'north-face-black' UNION ALL
SELECT id, '/winter/bluie northface.png', true, 0 FROM products WHERE slug = 'north-face-blue' UNION ALL
SELECT id, '/winter/white north face.png', true, 0 FROM products WHERE slug = 'north-face-white' UNION ALL
SELECT id, '/winter/brown.png', true, 0 FROM products WHERE slug = 'brown-winter-jacket' UNION ALL
SELECT id, '/winter/grey.png', true, 0 FROM products WHERE slug = 'grey-winter-jacket';
